version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: market_postgres
    environment:
      POSTGRES_USER: market_user
      POSTGRES_PASSWORD: market_pass
      POSTGRES_DB: market_db
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pg_data:
